/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.robolib.jni;

public class SWIGTYPE_Adapter {
  private long swigCPtr;

  public SWIGTYPE_Adapter(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_Adapter() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_Adapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}
